abstract final class TurkishLocations {
  static const Map<String, List<String>> provinces = {
    'Adana': ['Seyhan', 'Çukurova', 'Yüreğir', 'Sarıçam', 'Ceyhan'],
    'Adıyaman': ['Merkez', 'Kahta', 'Besni', 'Gölbaşı'],
    'Afyonkarahisar': ['Merkez', 'Sandıklı', 'Dinar', 'Bolvadin'],
    'Ağrı': ['Merkez', 'Doğubayazıt', 'Patnos', 'Eleşkirt'],
    'Aksaray': ['Merkez', 'Ortaköy', 'Eskil', 'Güzelyurt'],
    'Amasya': ['Merkez', 'Merzifon', 'Suluova', 'Taşova'],
    'Ankara': ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut'],
    'Antalya': ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Alanya', 'Manavgat'],
    'Ardahan': ['Merkez', 'Göle', 'Çıldır', 'Posof'],
    'Artvin': ['Merkez', 'Hopa', 'Arhavi', 'Borçka'],
    'Aydın': ['Efeler', 'Kuşadası', 'Nazilli', 'Söke', 'Didim'],
    'Balıkesir': ['Karesi', 'Altıeylül', 'Bandırma', 'Edremit', 'Ayvalık'],
    'Bartın': ['Merkez', 'Amasra', 'Ulus', 'Kurucaşile'],
    'Batman': ['Merkez', 'Kozluk', 'Beşiri', 'Sason'],
    'Bayburt': ['Merkez', 'Aydıntepe', 'Demirözü'],
    'Bilecik': ['Merkez', 'Bozüyük', 'Söğüt', 'Osmaneli'],
    'Bingöl': ['Merkez', 'Genç', 'Solhan', 'Karlıova'],
    'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Güroymak'],
    'Bolu': ['Merkez', 'Gerede', 'Mudurnu', 'Göynük'],
    'Burdur': ['Merkez', 'Bucak', 'Gölhisar', 'Yeşilova'],
    'Bursa': ['Osmangazi', 'Nilüfer', 'Yıldırım', 'İnegöl', 'Gemlik'],
    'Çanakkale': ['Merkez', 'Biga', 'Gelibolu', 'Çan', 'Ayvacık'],
    'Çankırı': ['Merkez', 'Çerkeş', 'Ilgaz', 'Şabanözü'],
    'Çorum': ['Merkez', 'Sungurlu', 'Osmancık', 'İskilip'],
    'Denizli': ['Pamukkale', 'Merkezefendi', 'Çivril', 'Acıpayam'],
    'Diyarbakır': ['Bağlar', 'Kayapınar', 'Yenişehir', 'Sur', 'Ergani'],
    'Düzce': ['Merkez', 'Akçakoca', 'Kaynaşlı', 'Gölyaka'],
    'Edirne': ['Merkez', 'Keşan', 'Uzunköprü', 'İpsala'],
    'Elazığ': ['Merkez', 'Kovancılar', 'Karakoçan', 'Palu'],
    'Erzincan': ['Merkez', 'Tercan', 'Üzümlü', 'Refahiye'],
    'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan'],
    'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Sivrihisar', 'Çifteler'],
    'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye'],
    'Giresun': ['Merkez', 'Bulancak', 'Espiye', 'Görele'],
    'Gümüşhane': ['Merkez', 'Kelkit', 'Şiran', 'Torul'],
    'Hakkâri': ['Merkez', 'Yüksekova', 'Şemdinli', 'Çukurca'],
    'Hatay': ['Antakya', 'İskenderun', 'Defne', 'Dörtyol', 'Samandağ'],
    'Iğdır': ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'],
    'Isparta': ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç'],
    'İstanbul': [
      'Kadıköy',
      'Beşiktaş',
      'Üsküdar',
      'Şişli',
      'Bakırköy',
      'Pendik',
      'Başakşehir',
    ],
    'İzmir': ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Çeşme'],
    'Kahramanmaraş': ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin'],
    'Karabük': ['Merkez', 'Safranbolu', 'Eskipazar', 'Yenice'],
    'Karaman': ['Merkez', 'Ermenek', 'Ayrancı', 'Kazımkarabekir'],
    'Kars': ['Merkez', 'Sarıkamış', 'Kağızman', 'Selim'],
    'Kastamonu': ['Merkez', 'Tosya', 'Taşköprü', 'İnebolu'],
    'Kayseri': [
      'Akkışla',
      'Bünyan',
      'Develi',
      'Felahiye',
      'Hacılar',
      'İncesu',
      'Kocasinan',
      'Melikgazi',
      'Özvatan',
      'Pınarbaşı',
      'Sarıoğlan',
      'Sarız',
      'Talas',
      'Tomarza',
      'Yahyalı',
      'Yeşilhisar',
    ],
    'Kilis': ['Merkez', 'Elbeyli', 'Musabeyli', 'Polateli'],
    'Kırıkkale': ['Merkez', 'Yahşihan', 'Keskin', 'Delice'],
    'Kırklareli': ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize'],
    'Kırşehir': ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı'],
    'Kocaeli': ['İzmit', 'Gebze', 'Darıca', 'Körfez', 'Başiskele'],
    'Konya': ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir'],
    'Kütahya': ['Merkez', 'Tavşanlı', 'Simav', 'Gediz'],
    'Malatya': ['Battalgazi', 'Yeşilyurt', 'Doğanşehir', 'Darende'],
    'Manisa': ['Şehzadeler', 'Yunusemre', 'Akhisar', 'Salihli', 'Turgutlu'],
    'Mardin': ['Artuklu', 'Kızıltepe', 'Midyat', 'Nusaybin'],
    'Mersin': ['Akdeniz', 'Mezitli', 'Yenişehir', 'Tarsus', 'Erdemli'],
    'Muğla': ['Menteşe', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas'],
    'Muş': ['Merkez', 'Bulanık', 'Malazgirt', 'Varto'],
    'Nevşehir': ['Merkez', 'Ürgüp', 'Avanos', 'Gülşehir'],
    'Niğde': ['Merkez', 'Bor', 'Ulukışla', 'Çiftlik'],
    'Ordu': ['Altınordu', 'Ünye', 'Fatsa', 'Perşembe'],
    'Osmaniye': ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe'],
    'Rize': ['Merkez', 'Çayeli', 'Ardeşen', 'Pazar'],
    'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Akyazı', 'Hendek'],
    'Samsun': ['İlkadım', 'Atakum', 'Canik', 'Bafra', 'Çarşamba'],
    'Siirt': ['Merkez', 'Kurtalan', 'Pervari', 'Baykan'],
    'Sinop': ['Merkez', 'Boyabat', 'Gerze', 'Ayancık'],
    'Sivas': ['Merkez', 'Şarkışla', 'Suşehri', 'Zara'],
    'Şanlıurfa': [
      'Haliliye',
      'Karaköprü',
      'Eyyübiye',
      'Suruç',
      'Akçakale',
      'Harran',
      'Ceylanpınar',
    ],
    'Şırnak': ['Merkez', 'Cizre', 'Silopi', 'İdil'],
    'Tekirdağ': ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Marmaraereğlisi'],
    'Tokat': ['Merkez', 'Erbaa', 'Turhal', 'Niksar'],
    'Trabzon': ['Ortahisar', 'Akçaabat', 'Araklı', 'Of'],
    'Tunceli': ['Merkez', 'Pertek', 'Ovacık', 'Mazgirt'],
    'Uşak': ['Merkez', 'Banaz', 'Eşme', 'Sivaslı'],
    'Van': ['İpekyolu', 'Edremit', 'Tuşba', 'Erciş'],
    'Yalova': ['Merkez', 'Çiftlikköy', 'Çınarcık', 'Altınova'],
    'Yozgat': ['Merkez', 'Sorgun', 'Akdağmadeni', 'Boğazlıyan'],
    'Zonguldak': ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek'],
  };

  static List<String> get provinceNames => provinces.keys.toList();

  static List<String> districtsFor(String province) =>
      provinces[province] ?? const [];
}

final Map<String, Map<String, List<String>>> ecoLocations = {
  for (final entry in TurkishLocations.provinces.entries)
    entry.key: {
      for (final district in entry.value) district: const ['Merkez'],
    },
};
